import type { Metadata } from "next";

import "./globals.css";

import { getServerSession } from "next-auth/next";
import { authOptions } from "@/auth";

import { AuthProvider } from "@/utils/authProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

   const session = await getServerSession(authOptions);
   
   
  
  return (
    <html lang="en">
      <body
        className={``}
      >
         <AuthProvider session={session} >{children}</AuthProvider>
         </body>
    </html>
  );
}
